name: comfy
channels:
  - bioconda
  - conda-forge
  - nodefaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgomp=15.2.0=he0feb66_16
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.1=h0c1763c_1
  - libuuid=2.41.3=h5347b49_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh8b19718_0
  - python=3.12.12=hd63d673_1_cpython
  - readline=8.3=h853b02a_0
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tzdata=2025c=h8577fbf_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
    - absl-py==2.3.1
    - addict==2.4.0
    - aiofiles==24.1.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.2
    - aiohttp-socks==0.11.0
    - aiosignal==1.4.0
    - albucore==0.0.24
    - albumentations==2.0.8
    - alembic==1.17.2
    - annotated-doc==0.0.4
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.12.0
    - attrs==25.4.0
    - av==16.0.1
    - certifi==2025.11.12
    - cffi==2.0.0
    - chardet==5.2.0
    - charset-normalizer==3.4.4
    - click==8.3.1
    - coloredlogs==15.0.1
    - colorlog==6.10.1
    - comfyui-embedded-docs==0.3.1
    - comfyui-frontend-package==1.35.9
    - comfyui-workflow-templates==0.7.64
    - comfyui-workflow-templates-core==0.3.61
    - comfyui-workflow-templates-media-api==0.3.34
    - comfyui-workflow-templates-media-image==0.3.43
    - comfyui-workflow-templates-media-other==0.3.62
    - comfyui-workflow-templates-media-video==0.3.22
    - contourpy==1.3.3
    - cryptography==46.0.3
    - cycler==0.12.1
    - cython==3.2.4
    - diffusers==0.36.0
    - dill==0.4.0
    - easydict==1.13
    - einops==0.8.1
    - embreex==2.17.7.post7
    - fastapi==0.128.0
    - filelock==3.20.1
    - flatbuffers==25.12.19
    - fonttools==4.61.1
    - frozenlist==1.8.0
    - fsspec==2025.12.0
    - ftfy==6.3.1
    - fvcore==0.1.5.post20221221
    - gitdb==4.0.12
    - gitpython==3.1.45
    - greenlet==3.3.0
    - h11==0.16.0
    - h2==4.3.0
    - hf-xet==1.2.0
    - hpack==4.1.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.36.0
    - humanfriendly==10.0
    - hydra-core==1.3.2
    - hyperframe==6.1.0
    - idna==3.11
    - imageio==2.37.2
    - importlib-metadata==8.7.1
    - insightface==0.7.3
    - iopath==0.1.10
    - jinja2==3.1.6
    - joblib==1.5.3
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.9.1
    - kiwisolver==1.4.9
    - kornia==0.8.2
    - kornia-rs==0.1.10
    - lazy-loader==0.4
    - llvmlite==0.46.0
    - lxml==6.0.2
    - mako==1.3.10
    - manifold3d==3.3.2
    - mapbox-earcut==2.0.0
    - markdown-it-py==4.0.0
    - markupsafe==3.0.3
    - matplotlib==3.10.8
    - matrix-nio==0.25.2
    - mdurl==0.1.2
    - mediapipe==0.10.31
    - ml-dtypes==0.5.4
    - mpmath==1.3.0
    - multidict==6.7.0
    - networkx==3.6.1
    - numba==0.63.1
    - numpy==2.2.6
    - nvidia-cublas-cu12==12.8.4.1
    - nvidia-cuda-cupti-cu12==12.8.90
    - nvidia-cuda-nvrtc-cu12==12.8.93
    - nvidia-cuda-runtime-cu12==12.8.90
    - nvidia-cudnn-cu12==9.10.2.21
    - nvidia-cufft-cu12==11.3.3.83
    - nvidia-cufile-cu12==1.13.1.3
    - nvidia-curand-cu12==10.3.9.90
    - nvidia-cusolver-cu12==11.7.3.90
    - nvidia-cusparse-cu12==12.5.8.93
    - nvidia-cusparselt-cu12==0.7.1
    - nvidia-nccl-cu12==2.27.5
    - nvidia-nvjitlink-cu12==12.8.93
    - nvidia-nvshmem-cu12==3.3.20
    - nvidia-nvtx-cu12==12.8.90
    - omegaconf==2.3.0
    - onnx==1.20.0
    - onnxruntime==1.23.2
    - opencv-python==4.12.0.88
    - opencv-python-headless==4.12.0.88
    - packaging==25.0
    - piexif==1.1.3
    - pillow==12.1.0
    - platformdirs==4.5.1
    - pooch==1.8.2
    - portalocker==3.2.0
    - prettytable==3.17.0
    - propcache==0.4.1
    - protobuf==6.33.2
    - psutil==7.2.0
    - pycollada==0.9.2
    - pycparser==2.23
    - pycryptodome==3.23.0
    - pydantic==2.12.5
    - pydantic-core==2.41.5
    - pydantic-settings==2.12.0
    - pygithub==2.8.1
    - pygments==2.19.2
    - pyjwt==2.10.1
    - pymatting==1.1.14
    - pynacl==1.6.1
    - pyparsing==3.3.1
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.2.1
    - python-multipart==0.0.21
    - python-socks==2.8.0
    - pyyaml==6.0.3
    - referencing==0.37.0
    - regex==2025.11.3
    - rembg==2.0.72
    - requests==2.32.5
    - rich==14.2.0
    - rpds-py==0.30.0
    - rtree==1.4.1
    - safetensors==0.7.0
    - sam-2==1.0
    - scikit-image==0.26.0
    - scikit-learn==1.8.0
    - scipy==1.16.3
    - segment-anything==1.0
    - sentencepiece==0.2.1
    - shapely==2.1.2
    - shellingham==1.5.4
    - simsimd==6.5.12
    - six==1.17.0
    - smmap==5.0.2
    - sounddevice==0.5.3
    - spandrel==0.4.1
    - sqlalchemy==2.0.45
    - starlette==0.50.0
    - stringzilla==4.6.0
    - svg-path==7.0
    - sympy==1.14.0
    - tabulate==0.9.0
    - termcolor==3.2.0
    - threadpoolctl==3.6.0
    - tifffile==2025.12.20
    - tokenizers==0.22.1
    - toml==0.10.2
    - torch==2.9.1
    - torchaudio==2.9.1
    - torchsde==0.2.6
    - torchvision==0.24.1
    - tqdm==4.67.1
    - trampoline==0.1.2
    - transformers==4.57.3
    - trimesh==4.10.1
    - triton==3.5.1
    - typer==0.21.0
    - typing-extensions==4.15.0
    - typing-inspection==0.4.2
    - unpaddedbase64==2.1.0
    - urllib3==2.6.2
    - uv==0.9.18
    - uvicorn==0.40.0
    - vhacdx==0.0.10
    - wcwidth==0.2.14
    - xxhash==3.6.0
    - yacs==0.1.8
    - yapf==0.43.0
    - yarl==1.22.0
    - zipp==3.23.0
prefix: /mnt/lustre/work/ponsmoll/pba966/conda/envs/comfy
